### ISSUE TITLE
Error: "Unable to download magento setup version"

### ISSUE THREAD

**Issue by Aquive** [redchamps/butter#1] opened 2020-11-30 12:22 UTC
I did config. And then ran install. I get below error. When I run the curl command manually I get an empty package. How can I solve this?

```
app@pup1cs-aquive-magweb-cmbl ~/butter $ butter magento:install 2.4.0
Installing Magento community version 2.4.0
-> Downloading package
Setup directory not exists .. creating
mkdir: cannot create directory ‘/data/web/butter/’: File exists
Done .. Created.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    25    0    25    0     0     32      0 --:--:-- --:--:-- --:--:--    32
Package already exists

In PlaceFiles.php line 53:
                                                                                                                   
  Unable to download magento setup version cd ~/butter/ && curl -O https://hidden:hidden@www.magentocommerce.com/products/downloads/file/Magento-CE-2.4.0.tar.gz              
                                                                                                                   

magento:install [--edition [EDITION]] [--method [METHOD]] [--sample-data [SAMPLE-DATA]] [--generate-profile [GENERATE-PROFILE]] [--] <version>
```

**Comment by rav-redchamps** [comment] 2020-11-30 12:24
Hi @Aquive 

May you please attach your config file here.

**Comment by Aquive** [comment] 2020-11-30 13:34
Thanks for support and fast reply btw.

```
<?php
/*
 * Don't change values like
 * <version>
 * <installation-path>
 * They're variables & will be replaced with dynamic values at runtime
 * */
return [
    'db' => [
        'table_prefix' => '',
        'connection' => [
            'host' => 'localhost',
            'dbname' => 'magento_<version>',
            'username' => 'app',
            'password' => 'MbGDlkeXtRo8soFkisF7Mi5da35dsGag32563',
            'port' => 3306
        ]
    ],
    /*
     * #Required
     * This required to download zip packages from Magento server, if you don't want to input these details
     * then change 'installation_method' setting to 'composer' instead of 'zip'
     * Login to your account on magento.com and generate it in Account Settings->Downloads Access Token
     * MageId can be found there as well
     * */
    'authentication' => [
        'token' => 'hidden',
        'mage_id' => 'hidden'
    ],
    'installation_root' => '/data/web/magento2/',
    'setup_directory' => '~/butter/',
    'base_url' => 'http://app.hypernode.io/',
    'zip_file' => [
        'ce_prefix' => 'Magento-CE-',
        'type'  => 'tar.gz'
    ],
    'installation_method' => "zip", //Allowed values zip, composer
    /*
     * Specify if performance profile needs to be generated for every installation
     * */
    'generate_performance_profile' => 'n', //allowed values n, small, medium, large, extra_large
    'installation_options' => [
        "frontname" => "admin",
        "admin-username" => "admin",
        "admin-password" => "password01",
        "admin-firstname" => "Admin",
        "admin-lastname" => "User",
        "admin-email" => "info@email.com"
    ],
    /*
     * Specify  composer package names of extra extensions if needs to be installed
     * For, example 'redchamps/module-easy-cache-clean' for
     * http://github.com/redchamps/easy-cache-clean
     * */
    'extra_extensions' => [

    ],
    /*
     * Enter additional commands that needs to ran after Magento installation
     * */
    'post_install_commands' => [

    ],
    /*
     * Config area for automatic nginx vhost generation
     * Set enabled to true & adjust other settings as per your environment
     * */
    'vhost' => [
        'enabled' => false, //allowed value true, false
        'nginx_path' => '/etc/nginx/',
        'server_restart_command' => 'service nginx restart',
        'vhost_config' => 'server {
              listen 80;
              server_name <domain>;
              set $MAGE_ROOT <installation-path>;
              include <installation-path>/nginx.conf.sample;
            }'
    ]
];

```

**Comment by rav-redchamps** [comment] 2020-12-02 08:16
Seems like problem is with reading or creating setup directory path "~/butter/". May you please try mentioning absolute path for the setup directory like /User/name/butter instead of using "~" for home location(please replace "/User/name" with your home path).

That might solve the problem.

**Comment by rav-redchamps** [comment] 2020-12-23 06:09
Hi @Aquive 

I hope the problem is resolved for you. Closing this issue for now, please feel free to reopen.

**Closed as completed by rav-redchamps** 2020-12-23 06:09 UTC

**Comment by Aquive** [comment] 2021-02-03 15:09
Thanks for the help. Just had time to test your suggestion. I changed `'setup_directory' => '~/butter/',` to `'setup_directory' => '/data/web/butter',`. Now I get following error.

```
 ~/butter $ butter magento:install 2.4.0
Installing Magento community version 2.4.0
-> Downloading package
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    25    0    25    0     0     29      0 --:--:-- --:--:-- --:--:--    29
Package already exists
-> Extracting filesystem
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

In PlaceFiles.php line 53:
                                                                                                      
  The command "cd /data/web/magento2/240 && tar xf /data/web/butter/Magento-CE-2.4.0.tar.gz" failed.  
                                                                                                      
  Exit Code: 2(Misuse of shell builtins)                                                              
                                                                                                      
  Working directory: /data/web/butter                                                                 
                                                                                                      
  Output:                                                                                             
  ================                                                                                    
                                                                                                      
                                                                                                      
  Error Output:                                                                                       
  ================                                                                                    
  tar: This does not look like a tar archive                                                          
                                                                                                      
  gzip: stdin: not in gzip format                                                                     
  tar: Child returned status 1                                                                        
  tar: Error is not recoverable: exiting now                                                          
                                                                                                      

magento:install [--edition [EDITION]] [--method [METHOD]] [--sample-data [SAMPLE-DATA]] [--generate-profile [GENERATE-PROFILE]] [--] <version>


```

When I look in the butter directory there is a file but its filesize is 0. How can I solve/fix this?

EDIT: 

I have been debugging. It seems that the zip archive is not downloading. When I try to download it manually with the browser it does not get authenticated. I checked the keys, they are working. I tried other keys. Same result. Something wrong with Magento site?
